import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const cmmcControls = [
  // Access Control (AC) - 22 controls
  {
    id: "AC.L1-3.1.1",
    domain: "Access Control",
    practice: "Limit system access to authorized users",
    level: 1,
    description: "Limit information system access to authorized users, processes acting on behalf of authorized users, or devices (including other information systems).",
    objective: "Prevent unauthorized access to organizational systems and data by ensuring only authorized entities can access the system.",
  },
  {
    id: "AC.L1-3.1.2",
    domain: "Access Control",
    practice: "Limit system access to the types of transactions and functions that authorized users are permitted to execute",
    level: 1,
    description: "Limit information system access to the types of transactions and functions that authorized users are permitted to execute.",
    objective: "Ensure users can only perform authorized actions on the system.",
  },
  {
    id: "AC.L2-3.1.3",
    domain: "Access Control",
    practice: "Control the flow of CUI in accordance with approved authorizations",
    level: 2,
    description: "Control the flow of CUI in accordance with approved authorizations.",
    objective: "Prevent unauthorized disclosure of CUI by controlling information flow.",
  },
  {
    id: "AC.L2-3.1.4",
    domain: "Access Control",
    practice: "Separate the duties of individuals to reduce the risk of malevolent activity",
    level: 2,
    description: "Separate the duties of individuals to reduce the risk of malevolent activity without collusion.",
    objective: "Prevent fraud and errors by requiring multiple people to complete critical tasks.",
  },
  {
    id: "AC.L2-3.1.5",
    domain: "Access Control",
    practice: "Employ the principle of least privilege",
    level: 2,
    description: "Employ the principle of least privilege, including specific security functions and privileged accounts.",
    objective: "Minimize the access granted to users to only what is necessary for their job function.",
  },
  {
    id: "AC.L2-3.1.6",
    domain: "Access Control",
    practice: "Use non-privileged accounts when accessing nonsecurity functions",
    level: 2,
    description: "Use non-privileged accounts or roles when accessing nonsecurity functions.",
    objective: "Reduce risk by limiting privileged account usage to only security functions.",
  },
  {
    id: "AC.L2-3.1.7",
    domain: "Access Control",
    practice: "Prevent non-privileged users from executing privileged functions",
    level: 2,
    description: "Prevent non-privileged users from executing privileged functions and audit the execution of such functions.",
    objective: "Control and monitor privileged operations to prevent unauthorized actions.",
  },
  {
    id: "AC.L2-3.1.8",
    domain: "Access Control",
    practice: "Limit unsuccessful logon attempts",
    level: 2,
    description: "Limit unsuccessful logon attempts.",
    objective: "Prevent brute force attacks by limiting login retry attempts.",
  },
  {
    id: "AC.L2-3.1.9",
    domain: "Access Control",
    practice: "Provide privacy and security notices",
    level: 2,
    description: "Provide privacy and security notices consistent with applicable CUI rules.",
    objective: "Inform users of their responsibilities regarding CUI handling.",
  },
  {
    id: "AC.L2-3.1.10",
    domain: "Access Control",
    practice: "Use session lock with pattern-hiding displays",
    level: 2,
    description: "Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.",
    objective: "Protect information from unauthorized viewing when systems are unattended.",
  },
  {
    id: "AC.L2-3.1.11",
    domain: "Access Control",
    practice: "Terminate user sessions after a defined period of inactivity",
    level: 2,
    description: "Terminate (automatically) a user session after a defined condition.",
    objective: "Reduce exposure of active sessions to unauthorized access.",
  },
  {
    id: "AC.L2-3.1.12",
    domain: "Access Control",
    practice: "Monitor and control remote access sessions",
    level: 2,
    description: "Monitor and control remote access sessions.",
    objective: "Ensure remote connections are authorized and secure.",
  },
  {
    id: "AC.L2-3.1.13",
    domain: "Access Control",
    practice: "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions",
    level: 2,
    description: "Employ cryptographic mechanisms to protect the confidentiality of remote access sessions.",
    objective: "Prevent interception of remote sessions through encryption.",
  },
  {
    id: "AC.L2-3.1.14",
    domain: "Access Control",
    practice: "Route remote access via managed access control points",
    level: 2,
    description: "Route remote access via managed access control points.",
    objective: "Centralize remote access through monitored and controlled entry points.",
  },
  {
    id: "AC.L2-3.1.15",
    domain: "Access Control",
    practice: "Authorize remote execution of privileged commands",
    level: 2,
    description: "Authorize remote execution of privileged commands and remote access to security-relevant information.",
    objective: "Control and monitor remote privileged operations.",
  },
  {
    id: "AC.L2-3.1.16",
    domain: "Access Control",
    practice: "Authorize wireless access prior to allowing connections",
    level: 2,
    description: "Authorize wireless access prior to allowing such connections.",
    objective: "Ensure wireless connections are authenticated before network access.",
  },
  {
    id: "AC.L2-3.1.17",
    domain: "Access Control",
    practice: "Protect wireless access using authentication and encryption",
    level: 2,
    description: "Protect wireless access using authentication and encryption.",
    objective: "Secure wireless communications from unauthorized access and eavesdropping.",
  },
  {
    id: "AC.L2-3.1.18",
    domain: "Access Control",
    practice: "Control connection of mobile devices",
    level: 2,
    description: "Control connection of mobile devices.",
    objective: "Manage risks associated with mobile device connectivity.",
  },
  {
    id: "AC.L2-3.1.19",
    domain: "Access Control",
    practice: "Encrypt CUI on mobile devices",
    level: 2,
    description: "Encrypt CUI on mobile devices and mobile computing platforms.",
    objective: "Protect CUI from unauthorized disclosure if mobile devices are lost or stolen.",
  },
  {
    id: "AC.L2-3.1.20",
    domain: "Access Control",
    practice: "Verify and control/limit connections to external systems",
    level: 2,
    description: "Verify and control/limit connections to and use of external information systems.",
    objective: "Manage security risks from external system connections.",
  },
  {
    id: "AC.L2-3.1.21",
    domain: "Access Control",
    practice: "Limit use of portable storage devices",
    level: 2,
    description: "Limit use of organizational portable storage devices on external systems.",
    objective: "Reduce risk of CUI exposure through portable storage.",
  },
  {
    id: "AC.L2-3.1.22",
    domain: "Access Control",
    practice: "Control CUI posted or processed on publicly accessible systems",
    level: 2,
    description: "Control CUI posted or processed on publicly accessible information systems.",
    objective: "Prevent unauthorized disclosure of CUI on public systems.",
  },

  // Awareness and Training (AT) - 4 controls
  {
    id: "AT.L2-3.2.1",
    domain: "Awareness and Training",
    practice: "Ensure that managers and users are aware of security risks",
    level: 2,
    description: "Ensure that managers, systems administrators, and users of organizational information systems are made aware of the security risks associated with their activities and of the applicable policies, standards, and procedures related to the security of those systems.",
    objective: "Build security awareness across all levels of the organization.",
  },
  {
    id: "AT.L2-3.2.2",
    domain: "Awareness and Training",
    practice: "Ensure that personnel are trained to carry out their assigned information security-related duties",
    level: 2,
    description: "Ensure that personnel are trained to carry out their assigned information security-related duties and responsibilities.",
    objective: "Provide necessary security training for job-specific duties.",
  },
  {
    id: "AT.L2-3.2.3",
    domain: "Awareness and Training",
    practice: "Provide security awareness training on recognizing and reporting potential indicators of insider threat",
    level: 2,
    description: "Provide security awareness training on recognizing and reporting potential indicators of insider threat.",
    objective: "Enable employees to identify and report suspicious insider activities.",
  },

  // Audit and Accountability (AU) - 9 controls
  {
    id: "AU.L2-3.3.1",
    domain: "Audit and Accountability",
    practice: "Create and retain system audit logs",
    level: 2,
    description: "Create, protect, and retain information system audit records to the extent needed to enable monitoring, analysis, investigation, and reporting of unlawful, unauthorized, or inappropriate information system activity.",
    objective: "Maintain audit trails for security event investigation and analysis.",
  },
  {
    id: "AU.L2-3.3.2",
    domain: "Audit and Accountability",
    practice: "Ensure that actions of individual users can be traced",
    level: 2,
    description: "Ensure that the actions of individual information system users can be uniquely traced to those users so they can be held accountable for their actions.",
    objective: "Enable accountability through individual user action tracking.",
  },
  {
    id: "AU.L2-3.3.3",
    domain: "Audit and Accountability",
    practice: "Review and update logged events",
    level: 2,
    description: "Review and update logged events.",
    objective: "Ensure audit logs capture relevant security events.",
  },
  {
    id: "AU.L2-3.3.4",
    domain: "Audit and Accountability",
    practice: "Alert in the event of an audit logging process failure",
    level: 2,
    description: "Alert in the event of an audit logging process failure.",
    objective: "Ensure continuous audit capability through failure alerts.",
  },
  {
    id: "AU.L2-3.3.5",
    domain: "Audit and Accountability",
    practice: "Correlate audit record review, analysis, and reporting",
    level: 2,
    description: "Correlate audit record review, analysis, and reporting processes for investigation and response to indications of inappropriate, suspicious, or unusual activity.",
    objective: "Identify security incidents through audit analysis.",
  },
  {
    id: "AU.L2-3.3.6",
    domain: "Audit and Accountability",
    practice: "Provide audit record reduction and report generation",
    level: 2,
    description: "Provide audit record reduction and report generation to support on-demand analysis and reporting.",
    objective: "Enable efficient security event analysis and reporting.",
  },
  {
    id: "AU.L2-3.3.7",
    domain: "Audit and Accountability",
    practice: "Provide a system capability that compares and synchronizes internal system clocks",
    level: 2,
    description: "Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate time stamps for audit records.",
    objective: "Ensure accurate timestamps for audit correlation.",
  },
  {
    id: "AU.L2-3.3.8",
    domain: "Audit and Accountability",
    practice: "Protect audit information and audit logging tools",
    level: 2,
    description: "Protect audit information and audit logging tools from unauthorized access, modification, and deletion.",
    objective: "Preserve integrity of audit records and tools.",
  },
  {
    id: "AU.L2-3.3.9",
    domain: "Audit and Accountability",
    practice: "Limit management of audit logging to a subset of privileged users",
    level: 2,
    description: "Limit management of audit logging functionality to a subset of privileged users.",
    objective: "Control who can modify audit configurations.",
  },

  // Configuration Management (CM) - 11 controls
  {
    id: "CM.L2-3.4.1",
    domain: "Configuration Management",
    practice: "Establish and maintain baseline configurations",
    level: 2,
    description: "Establish and maintain baseline configurations and inventories of organizational information systems (including hardware, software, firmware, and documentation) throughout the respective system development life cycles.",
    objective: "Maintain known-good system configurations for security and change management.",
  },
  {
    id: "CM.L2-3.4.2",
    domain: "Configuration Management",
    practice: "Establish and enforce security configuration settings",
    level: 2,
    description: "Establish and enforce security configuration settings for information technology products employed in organizational information systems.",
    objective: "Ensure systems are configured securely according to security standards.",
  },
  {
    id: "CM.L2-3.4.3",
    domain: "Configuration Management",
    practice: "Track, review, approve/disapprove, and audit changes to systems",
    level: 2,
    description: "Track, review, approve/disapprove, and audit changes to information systems.",
    objective: "Control system changes to prevent unauthorized or harmful modifications.",
  },
  {
    id: "CM.L2-3.4.4",
    domain: "Configuration Management",
    practice: "Analyze the security impact of changes prior to implementation",
    level: 2,
    description: "Analyze the security impact of changes prior to implementation.",
    objective: "Prevent security degradation through change analysis.",
  },
  {
    id: "CM.L2-3.4.5",
    domain: "Configuration Management",
    practice: "Define, document, approve, and enforce physical and logical access restrictions",
    level: 2,
    description: "Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational information systems.",
    objective: "Control who can make changes to systems.",
  },
  {
    id: "CM.L2-3.4.6",
    domain: "Configuration Management",
    practice: "Employ the principle of least functionality",
    level: 2,
    description: "Employ the principle of least functionality by configuring organizational information systems to provide only essential capabilities.",
    objective: "Reduce attack surface by disabling unnecessary features.",
  },
  {
    id: "CM.L2-3.4.7",
    domain: "Configuration Management",
    practice: "Restrict, disable, or prevent the use of nonessential programs",
    level: 2,
    description: "Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.",
    objective: "Minimize potential attack vectors through system hardening.",
  },
  {
    id: "CM.L2-3.4.8",
    domain: "Configuration Management",
    practice: "Apply deny-by-exception policy to prevent the use of unauthorized software",
    level: 2,
    description: "Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software or deny-all, permit-by-exception (whitelisting) policy to allow the execution of authorized software.",
    objective: "Control which software can execute on organizational systems.",
  },
  {
    id: "CM.L2-3.4.9",
    domain: "Configuration Management",
    practice: "Control and monitor user-installed software",
    level: 2,
    description: "Control and monitor user-installed software.",
    objective: "Prevent installation of unauthorized or malicious software by users.",
  },

  // Identification and Authentication (IA) - 11 controls
  {
    id: "IA.L1-3.5.1",
    domain: "Identification and Authentication",
    practice: "Identify system users",
    level: 1,
    description: "Identify information system users, processes acting on behalf of users, or devices.",
    objective: "Establish unique identity for all system entities.",
  },
  {
    id: "IA.L1-3.5.2",
    domain: "Identification and Authentication",
    practice: "Authenticate the identities of users and devices",
    level: 1,
    description: "Authenticate (or verify) the identities of those users, processes, or devices, as a prerequisite to allowing access to organizational information systems.",
    objective: "Verify claimed identities before granting access.",
  },
  {
    id: "IA.L2-3.5.3",
    domain: "Identification and Authentication",
    practice: "Use multifactor authentication",
    level: 2,
    description: "Use multifactor authentication for local and network access to privileged accounts and for network access to non-privileged accounts.",
    objective: "Strengthen authentication through multiple verification factors.",
  },
  {
    id: "IA.L2-3.5.4",
    domain: "Identification and Authentication",
    practice: "Employ replay-resistant authentication mechanisms",
    level: 2,
    description: "Employ replay-resistant authentication mechanisms for network access to privileged and non-privileged accounts.",
    objective: "Prevent authentication replay attacks.",
  },
  {
    id: "IA.L2-3.5.5",
    domain: "Identification and Authentication",
    practice: "Prevent reuse of identifiers for a defined period",
    level: 2,
    description: "Prevent reuse of identifiers for a defined period.",
    objective: "Reduce confusion and potential access control errors from reused identities.",
  },
  {
    id: "IA.L2-3.5.6",
    domain: "Identification and Authentication",
    practice: "Disable identifiers after a defined period of inactivity",
    level: 2,
    description: "Disable identifiers after a defined period of inactivity.",
    objective: "Reduce attack surface by removing inactive accounts.",
  },
  {
    id: "IA.L2-3.5.7",
    domain: "Identification and Authentication",
    practice: "Enforce a minimum password complexity",
    level: 2,
    description: "Enforce a minimum password complexity and change of characters when new passwords are created.",
    objective: "Ensure passwords resist guessing and cracking attacks.",
  },
  {
    id: "IA.L2-3.5.8",
    domain: "Identification and Authentication",
    practice: "Prohibit password reuse",
    level: 2,
    description: "Prohibit password reuse for a specified number of generations.",
    objective: "Prevent use of compromised passwords from previous breaches.",
  },
  {
    id: "IA.L2-3.5.9",
    domain: "Identification and Authentication",
    practice: "Allow temporary password use for system logons",
    level: 2,
    description: "Allow temporary password use for system logons with an immediate change to a permanent password.",
    objective: "Ensure temporary passwords are changed to user-controlled passwords.",
  },
  {
    id: "IA.L2-3.5.10",
    domain: "Identification and Authentication",
    practice: "Store and transmit only cryptographically-protected passwords",
    level: 2,
    description: "Store and transmit only cryptographically-protected passwords.",
    objective: "Protect passwords from unauthorized disclosure.",
  },
  {
    id: "IA.L2-3.5.11",
    domain: "Identification and Authentication",
    practice: "Obscure feedback of authentication information",
    level: 2,
    description: "Obscure feedback of authentication information.",
    objective: "Prevent observation of authentication credentials during entry.",
  },

  // Incident Response (IR) - 8 controls
  {
    id: "IR.L2-3.6.1",
    domain: "Incident Response",
    practice: "Establish an operational incident-handling capability",
    level: 2,
    description: "Establish an operational incident-handling capability for organizational information systems that includes adequate preparation, detection, analysis, containment, recovery, and user response activities.",
    objective: "Ensure organization can effectively respond to security incidents.",
  },
  {
    id: "IR.L2-3.6.2",
    domain: "Incident Response",
    practice: "Track, document, and report incidents",
    level: 2,
    description: "Track, document, and report incidents to appropriate officials and/or authorities.",
    objective: "Maintain records and notify stakeholders of security incidents.",
  },
  {
    id: "IR.L2-3.6.3",
    domain: "Incident Response",
    practice: "Test the organizational incident response capability",
    level: 2,
    description: "Test the organizational incident response capability.",
    objective: "Validate incident response procedures through testing.",
  },

  // Maintenance (MA) - 6 controls
  {
    id: "MA.L2-3.7.1",
    domain: "Maintenance",
    practice: "Perform maintenance on systems",
    level: 2,
    description: "Perform maintenance on organizational information systems.",
    objective: "Ensure systems remain operational and secure through regular maintenance.",
  },
  {
    id: "MA.L2-3.7.2",
    domain: "Maintenance",
    practice: "Provide controls on the tools used for maintenance",
    level: 2,
    description: "Provide controls on the tools, techniques, mechanisms, and personnel used to conduct information system maintenance.",
    objective: "Secure maintenance activities and tools from exploitation.",
  },
  {
    id: "MA.L2-3.7.3",
    domain: "Maintenance",
    practice: "Ensure equipment removed for off-site maintenance is sanitized",
    level: 2,
    description: "Ensure equipment removed for off-site maintenance is sanitized of any CUI.",
    objective: "Prevent CUI disclosure through equipment maintenance.",
  },
  {
    id: "MA.L2-3.7.4",
    domain: "Maintenance",
    practice: "Check media containing diagnostic and test programs for malicious code",
    level: 2,
    description: "Check media containing diagnostic and test programs for malicious code before the media are used in organizational information systems.",
    objective: "Prevent malware introduction through maintenance media.",
  },
  {
    id: "MA.L2-3.7.5",
    domain: "Maintenance",
    practice: "Require multifactor authentication to establish nonlocal maintenance sessions",
    level: 2,
    description: "Require multifactor authentication to establish nonlocal maintenance sessions via external network connections and terminate such connections when nonlocal maintenance is complete.",
    objective: "Secure remote maintenance access through strong authentication.",
  },
  {
    id: "MA.L2-3.7.6",
    domain: "Maintenance",
    practice: "Supervise the maintenance activities of personnel without required access authorization",
    level: 2,
    description: "Supervise the maintenance activities of maintenance personnel without required access authorization.",
    objective: "Prevent unauthorized access during maintenance by uncleared personnel.",
  },

  // Media Protection (MP) - 7 controls
  {
    id: "MP.L2-3.8.1",
    domain: "Media Protection",
    practice: "Protect system media",
    level: 2,
    description: "Protect (i.e., physically control and securely store) information system media containing CUI, both paper and digital.",
    objective: "Prevent unauthorized access to CUI on media.",
  },
  {
    id: "MP.L2-3.8.2",
    domain: "Media Protection",
    practice: "Limit access to CUI on system media to authorized users",
    level: 2,
    description: "Limit access to CUI on information system media to authorized users.",
    objective: "Control who can access CUI stored on media.",
  },
  {
    id: "MP.L2-3.8.3",
    domain: "Media Protection",
    practice: "Sanitize or destroy system media before disposal or reuse",
    level: 2,
    description: "Sanitize or destroy information system media containing CUI before disposal or release for reuse.",
    objective: "Prevent CUI disclosure through disposed or reused media.",
  },
  {
    id: "MP.L2-3.8.4",
    domain: "Media Protection",
    practice: "Mark media with CUI markings",
    level: 2,
    description: "Mark media with necessary CUI markings and distribution limitations.",
    objective: "Ensure proper handling of media containing CUI through labeling.",
  },
  {
    id: "MP.L2-3.8.5",
    domain: "Media Protection",
    practice: "Control access to media containing CUI and maintain accountability",
    level: 2,
    description: "Control access to media containing CUI and maintain accountability for media during transport outside of controlled areas.",
    objective: "Prevent loss or unauthorized access to CUI during transport.",
  },
  {
    id: "MP.L2-3.8.6",
    domain: "Media Protection",
    practice: "Implement cryptographic mechanisms to protect CUI stored on digital media",
    level: 2,
    description: "Implement cryptographic mechanisms to protect the confidentiality of CUI stored on digital media during transport unless otherwise protected by alternative physical safeguards.",
    objective: "Protect CUI on transported media through encryption.",
  },
  {
    id: "MP.L2-3.8.7",
    domain: "Media Protection",
    practice: "Control the use of removable media on system components",
    level: 2,
    description: "Control the use of removable media on information system components.",
    objective: "Prevent unauthorized data transfer via removable media.",
  },
  {
    id: "MP.L2-3.8.8",
    domain: "Media Protection",
    practice: "Prohibit the use of portable storage devices when such devices have no identifiable owner",
    level: 2,
    description: "Prohibit the use of portable storage devices when such devices have no identifiable owner.",
    objective: "Prevent use of potentially malicious unknown devices.",
  },
  {
    id: "MP.L2-3.8.9",
    domain: "Media Protection",
    practice: "Protect the confidentiality of backup CUI at storage locations",
    level: 2,
    description: "Protect the confidentiality of backup CUI at storage locations.",
    objective: "Ensure backup data is protected from unauthorized access.",
  },

  // Personnel Security (PS) - 2 controls
  {
    id: "PS.L2-3.9.1",
    domain: "Personnel Security",
    practice: "Screen individuals prior to authorizing access to systems containing CUI",
    level: 2,
    description: "Screen individuals prior to authorizing access to organizational information systems containing CUI.",
    objective: "Reduce insider threat risk through personnel screening.",
  },
  {
    id: "PS.L2-3.9.2",
    domain: "Personnel Security",
    practice: "Ensure that CUI is protected during and after personnel actions",
    level: 2,
    description: "Ensure that organizational information and information systems containing CUI are protected during and after personnel actions such as terminations and transfers.",
    objective: "Prevent CUI disclosure during personnel transitions.",
  },

  // Physical Protection (PE) - 6 controls
  {
    id: "PE.L1-3.10.1",
    domain: "Physical Protection",
    practice: "Limit physical access to organizational systems and facilities",
    level: 1,
    description: "Limit physical access to organizational information systems, equipment, and the respective operating environments to authorized individuals.",
    objective: "Prevent unauthorized physical access to systems and facilities.",
  },
  {
    id: "PE.L1-3.10.2",
    domain: "Physical Protection",
    practice: "Protect and monitor the physical facility and support infrastructure",
    level: 1,
    description: "Protect and monitor the physical facility and support infrastructure for organizational information systems.",
    objective: "Safeguard facilities housing organizational systems.",
  },
  {
    id: "PE.L2-3.10.3",
    domain: "Physical Protection",
    practice: "Escort visitors and monitor visitor activity",
    level: 2,
    description: "Escort visitors and monitor visitor activity.",
    objective: "Prevent unauthorized access by visitors to sensitive areas.",
  },
  {
    id: "PE.L2-3.10.4",
    domain: "Physical Protection",
    practice: "Maintain audit logs of physical access",
    level: 2,
    description: "Maintain audit logs of physical access.",
    objective: "Track physical access for security investigation and compliance.",
  },
  {
    id: "PE.L2-3.10.5",
    domain: "Physical Protection",
    practice: "Control and manage physical access devices",
    level: 2,
    description: "Control and manage physical access devices.",
    objective: "Ensure physical access controls remain effective.",
  },
  {
    id: "PE.L2-3.10.6",
    domain: "Physical Protection",
    practice: "Enforce safeguarding measures for CUI at alternate work sites",
    level: 2,
    description: "Enforce safeguarding measures for CUI at alternate work sites (e.g., telework sites).",
    objective: "Protect CUI when work is performed outside primary facilities.",
  },

  // Risk Assessment (RA) - 3 controls
  {
    id: "RA.L2-3.11.1",
    domain: "Risk Assessment",
    practice: "Periodically assess the risk to organizational operations",
    level: 2,
    description: "Periodically assess the risk to organizational operations (including mission, functions, image, or reputation), organizational assets, and individuals, resulting from the operation of organizational information systems and the associated processing, storage, or transmission of CUI.",
    objective: "Identify and understand security risks to the organization.",
  },
  {
    id: "RA.L2-3.11.2",
    domain: "Risk Assessment",
    practice: "Scan for vulnerabilities in systems",
    level: 2,
    description: "Scan for vulnerabilities in organizational information systems and applications periodically and when new vulnerabilities affecting those systems and applications are identified.",
    objective: "Identify technical vulnerabilities that could be exploited.",
  },
  {
    id: "RA.L2-3.11.3",
    domain: "Risk Assessment",
    practice: "Remediate vulnerabilities in accordance with risk assessments",
    level: 2,
    description: "Remediate vulnerabilities in accordance with risk assessments.",
    objective: "Address identified vulnerabilities based on risk priority.",
  },

  // Security Assessment (CA) - 9 controls
  {
    id: "CA.L2-3.12.1",
    domain: "Security Assessment",
    practice: "Periodically assess security controls",
    level: 2,
    description: "Periodically assess the security controls in organizational information systems to determine if the controls are effective in their application.",
    objective: "Verify security controls function as intended.",
  },
  {
    id: "CA.L2-3.12.2",
    domain: "Security Assessment",
    practice: "Develop and implement plans of action to correct deficiencies",
    level: 2,
    description: "Develop and implement plans of action designed to correct deficiencies and reduce or eliminate vulnerabilities in organizational information systems.",
    objective: "Address identified security weaknesses systematically.",
  },
  {
    id: "CA.L2-3.12.3",
    domain: "Security Assessment",
    practice: "Monitor security controls on an ongoing basis",
    level: 2,
    description: "Monitor security controls on an ongoing basis to ensure the continued effectiveness of the controls.",
    objective: "Ensure security controls remain effective over time.",
  },
  {
    id: "CA.L2-3.12.4",
    domain: "Security Assessment",
    practice: "Develop, document, and periodically update system security plans",
    level: 2,
    description: "Develop, document, and periodically update system security plans that describe system boundaries, system environments of operation, how security requirements are implemented, and the relationships with or connections to other systems.",
    objective: "Maintain documentation of system security posture.",
  },

  // System and Communications Protection (SC) - 25 controls
  {
    id: "SC.L1-3.13.1",
    domain: "System and Communications Protection",
    practice: "Monitor, control, and protect communications at external and internal boundaries",
    level: 1,
    description: "Monitor, control, and protect organizational communications (i.e., information transmitted or received by organizational information systems) at the external boundaries and key internal boundaries of the information systems.",
    objective: "Secure network communications at critical boundaries.",
  },
  {
    id: "SC.L1-3.13.2",
    domain: "System and Communications Protection",
    practice: "Employ architectural designs that promote effective security",
    level: 1,
    description: "Employ architectural designs, software development techniques, and systems engineering principles that promote effective information security within organizational information systems.",
    objective: "Build security into system architecture and design.",
  },
  {
    id: "SC.L2-3.13.3",
    domain: "System and Communications Protection",
    practice: "Separate user functionality from system management functionality",
    level: 2,
    description: "Separate user functionality (including user interface services) from information system management functionality.",
    objective: "Isolate administrative functions from user operations.",
  },
  {
    id: "SC.L2-3.13.4",
    domain: "System and Communications Protection",
    practice: "Prevent unauthorized information transfer via shared resources",
    level: 2,
    description: "Prevent unauthorized and unintended information transfer via shared system resources.",
    objective: "Prevent information leakage through resource sharing.",
  },
  {
    id: "SC.L2-3.13.5",
    domain: "System and Communications Protection",
    practice: "Implement subnetworks for publicly accessible components",
    level: 2,
    description: "Implement subnetworks for publicly accessible system components that are physically or logically separated from internal networks.",
    objective: "Isolate public-facing systems from internal networks.",
  },
  {
    id: "SC.L2-3.13.6",
    domain: "System and Communications Protection",
    practice: "Deny network communications traffic by default",
    level: 2,
    description: "Deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).",
    objective: "Implement restrictive firewall policies.",
  },
  {
    id: "SC.L2-3.13.7",
    domain: "System and Communications Protection",
    practice: "Prevent remote devices from simultaneously establishing connections",
    level: 2,
    description: "Prevent remote devices from simultaneously establishing non-remote connections with organizational information systems and communicating via some other connection to resources in external networks.",
    objective: "Prevent split tunneling that bypasses security controls.",
  },
  {
    id: "SC.L2-3.13.8",
    domain: "System and Communications Protection",
    practice: "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI",
    level: 2,
    description: "Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI during transmission unless otherwise protected by alternative physical safeguards.",
    objective: "Protect CUI in transit through encryption.",
  },
  {
    id: "SC.L2-3.13.9",
    domain: "System and Communications Protection",
    practice: "Terminate network connections at the end of sessions",
    level: 2,
    description: "Terminate network connections associated with communications sessions at the end of the sessions or after a defined period of inactivity.",
    objective: "Reduce exposure from active network sessions.",
  },
  {
    id: "SC.L2-3.13.10",
    domain: "System and Communications Protection",
    practice: "Establish and manage cryptographic keys",
    level: 2,
    description: "Establish and manage cryptographic keys for cryptography employed in organizational information systems.",
    objective: "Ensure proper management of encryption keys.",
  },
  {
    id: "SC.L2-3.13.11",
    domain: "System and Communications Protection",
    practice: "Employ FIPS-validated cryptography",
    level: 2,
    description: "Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.",
    objective: "Use approved cryptographic standards for CUI protection.",
  },
  {
    id: "SC.L2-3.13.12",
    domain: "System and Communications Protection",
    practice: "Prohibit remote activation of collaborative computing devices",
    level: 2,
    description: "Prohibit remote activation of collaborative computing devices and provide indication of devices in use to users present at the device.",
    objective: "Prevent unauthorized remote surveillance through collaboration tools.",
  },
  {
    id: "SC.L2-3.13.13",
    domain: "System and Communications Protection",
    practice: "Control and monitor the use of mobile code",
    level: 2,
    description: "Control and monitor the use of mobile code.",
    objective: "Manage security risks from executable code.",
  },
  {
    id: "SC.L2-3.13.14",
    domain: "System and Communications Protection",
    practice: "Control and monitor the use of VoIP",
    level: 2,
    description: "Control and monitor the use of Voice over Internet Protocol (VoIP) technologies.",
    objective: "Secure voice communications over IP networks.",
  },
  {
    id: "SC.L2-3.13.15",
    domain: "System and Communications Protection",
    practice: "Protect the authenticity of communications sessions",
    level: 2,
    description: "Protect the authenticity of communications sessions.",
    objective: "Prevent session hijacking and man-in-the-middle attacks.",
  },
  {
    id: "SC.L2-3.13.16",
    domain: "System and Communications Protection",
    practice: "Protect the confidentiality of CUI at rest",
    level: 2,
    description: "Protect the confidentiality of CUI at rest.",
    objective: "Protect stored CUI from unauthorized disclosure.",
  },

  // System and Information Integrity (SI) - 17 controls
  {
    id: "SI.L1-3.14.1",
    domain: "System and Information Integrity",
    practice: "Identify, report, and correct system flaws",
    level: 1,
    description: "Identify, report, and correct information and information system flaws in a timely manner.",
    objective: "Remediate system vulnerabilities promptly.",
  },
  {
    id: "SI.L1-3.14.2",
    domain: "System and Information Integrity",
    practice: "Provide protection from malicious code",
    level: 1,
    description: "Provide protection from malicious code at appropriate locations within organizational information systems.",
    objective: "Detect and prevent malware infections.",
  },
  {
    id: "SI.L1-3.14.3",
    domain: "System and Information Integrity",
    practice: "Monitor system security alerts and take appropriate actions",
    level: 1,
    description: "Monitor information system security alerts and advisories and take appropriate actions in response.",
    objective: "Stay informed and respond to security threats.",
  },
  {
    id: "SI.L2-3.14.4",
    domain: "System and Information Integrity",
    practice: "Update malicious code protection mechanisms",
    level: 2,
    description: "Update malicious code protection mechanisms when new releases are available.",
    objective: "Maintain current malware defenses.",
  },
  {
    id: "SI.L2-3.14.5",
    domain: "System and Information Integrity",
    practice: "Perform periodic scans and real-time scans of files",
    level: 2,
    description: "Perform periodic scans of the information system and real-time scans of files from external sources as files are downloaded, opened, or executed.",
    objective: "Detect malware through scanning.",
  },
  {
    id: "SI.L2-3.14.6",
    domain: "System and Information Integrity",
    practice: "Monitor system security for atypical use",
    level: 2,
    description: "Monitor organizational information systems, including inbound and outbound communications traffic, to detect attacks and indicators of potential attacks.",
    objective: "Identify security incidents through monitoring.",
  },
  {
    id: "SI.L2-3.14.7",
    domain: "System and Information Integrity",
    practice: "Identify unauthorized use of the system",
    level: 2,
    description: "Identify unauthorized use of organizational information systems.",
    objective: "Detect misuse of organizational resources.",
  },
];

async function main() {
  console.log("🌱 Seeding CMMC controls...");

  let createdCount = 0;
  let skippedCount = 0;

  for (const control of cmmcControls) {
    try {
      await prisma.cMMCControl.create({
        data: control,
      });
      createdCount++;
      console.log(`✅ Created: ${control.id} - ${control.practice}`);
    } catch (error: any) {
      if (error.code === "P2002") {
        // Unique constraint violation - control already exists
        skippedCount++;
        console.log(`⏭️  Skipped (already exists): ${control.id}`);
      } else {
        console.error(`❌ Error creating ${control.id}:`, error.message);
      }
    }
  }

  console.log("\n✨ Seeding complete!");
  console.log(`   Created: ${createdCount} controls`);
  console.log(`   Skipped: ${skippedCount} controls (already exist)`);
  console.log(`   Total: ${cmmcControls.length} controls processed`);
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
